//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTM.DBAccess.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMToolMapperDBEntities : DbContext
    {
        public PMToolMapperDBEntities()
            : base("name=PMToolMapperDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllFeature> AllFeatures { get; set; }
        public virtual DbSet<MappingHistoryDetail> MappingHistoryDetails { get; set; }
        public virtual DbSet<PMTool> PMTools { get; set; }
        public virtual DbSet<ToolFeatureCategory> ToolFeatureCategories { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
        public virtual DbSet<ToolFeature> ToolFeatures { get; set; }
        public virtual DbSet<MappingHistory> MappingHistories { get; set; }
        public virtual DbSet<MigrationHistory> MigrationHistories { get; set; }
    }
}
