//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTM.DBAccess.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolFeature
    {
        public long Id { get; set; }
        public Nullable<long> FeatureId { get; set; }
        public Nullable<long> FeatureCategoryId { get; set; }
        public Nullable<long> ToolId { get; set; }
        public string FeatureUrl { get; set; }
        public string FeatureStatus { get; set; }
        public string Date { get; set; }
    
        public virtual AllFeature AllFeature { get; set; }
        public virtual PMTool PMTool { get; set; }
        public virtual ToolFeatureCategory ToolFeatureCategory { get; set; }
    }
}
